import type { Metadata } from "next";
import { siteConfig } from "./site";

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} — Real-Time GPS Tracking in the Philippines`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.shortDescription,
  keywords: [
    "GPS tracker Philippines",
    "fleet management",
    "vehicle tracking",
    "truck GPS",
    "vehicle recovery",
    "TrackPro",
    "GPS Cagayan de Oro",
    "Philippine fleet tracking",
  ],
  applicationName: siteConfig.name,
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  publisher: siteConfig.name,
  category: "Technology",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: `${siteConfig.name} — Anti-Jammer GPS Tracker, Philippines`,
    description: siteConfig.shortDescription,
    // Image is generated by app/opengraph-image.tsx automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} — Anti-Jammer GPS Tracker`,
    description: siteConfig.shortDescription,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: siteConfig.name,
    url: siteConfig.url,
    description: siteConfig.longDescription,
    telephone: [siteConfig.contact.phonePrimary, siteConfig.contact.phoneSecondary],
    email: siteConfig.contact.email,
    address: {
      "@type": "PostalAddress",
      streetAddress: siteConfig.location.address,
      addressLocality: siteConfig.location.city,
      addressRegion: siteConfig.location.region,
      addressCountry: siteConfig.location.country,
    },
    sameAs: [siteConfig.social.facebook],
    areaServed: siteConfig.location.country,
  };
}
